vae:
  batch_size: 64
  n_cpu: 8
  img_channels: 3
  latent_size: 64
  img_size: 64
  lr: 1e-3
  wd: 1e-5
  log_images: 24
  n_epochs: 100
  data_dir: ${oc.env:TRAIN_DATASET_PATH}/gridworld.npz

mdrnn:
  latents: ${vae.latent_size} #latent size, the same we use for vae
  actions: 3
  hiddens: 256 #hidden size
  gaussians: 5
  rewards_terminal: False
  n_epochs: 20